language: emacs-lisp
before_install:
  # PPA for stable Emacs 25
  - sudo apt-add-repository -y ppa:adrozdoff/emacs
  # PPA for Emacs nightlies
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el

env:
  - EMACS=emacs25
  - EMACS=emacs-snapshot
script:
  - emacs --version
  - make update
  - make test
